# Generated by Django 5.0.2 on 2024-03-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='english_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text',
            new_name='morse_text',
        ),
    ]
